package ShoesManager.GUI;

import java.awt.Font;
import javax.swing.ImageIcon;

/**
 *
 * @author HiamKaito
 */
public class UserInfor extends javax.swing.JFrame {

    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblHovaTen;
    private javax.swing.JLabel lblchucvu;
    private javax.swing.JLabel lblemail;
    private javax.swing.JLabel lblgioitinh;
    private javax.swing.JLabel lblid;
    private javax.swing.JLabel lblluong;
    
    /**
     * Creates new form UserInfor
     */
    public UserInfor() {
        initComponents();
        init();
    }

    public void init() {
        lblHovaTen.setText(Memory.nhanvien.getStrHo() + " " + Memory.nhanvien.getStrTen());
        lblchucvu.setText(Memory.nhanvien.getStrChucVu());
        lblemail.setText(Memory.nhanvien.getStrEmail());
        lblgioitinh.setText(Memory.nhanvien.getStrGioiTinh());
        lblid.setText(Memory.nhanvien.getstrMaNV());
        lblluong.setText( String.valueOf(Memory.nhanvien.getiLuong()));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        lblgioitinh = new javax.swing.JLabel();
        lblchucvu = new javax.swing.JLabel();
        lblluong = new javax.swing.JLabel();
        lblemail = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblid = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lblHovaTen = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel(new ImageIcon("./src/ShoesManager/images/Avatar/130_100/" +
            Memory.nhanvien.getStrAnh() + ".png"));

    setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    setTitle("Thông tin");
    setBackground(new java.awt.Color(245, 247, 250));
    setMinimumSize(new java.awt.Dimension(280, 450));
    setResizable(false);
    getContentPane().setBackground(new java.awt.Color(245, 247, 250));

    jPanel1.setBackground(new java.awt.Color(255, 255, 255));
    jPanel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 20, 20, 20));

    jLabel9.setFont(new java.awt.Font("Segoe UI", Font.BOLD, 14)); // NOI18N
    jLabel9.setForeground(new java.awt.Color(100, 100, 100));
    jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
    jLabel9.setText("Lương:");

    lblgioitinh.setFont(new java.awt.Font("Segoe UI", Font.PLAIN, 14)); // NOI18N
    lblgioitinh.setForeground(new java.awt.Color(44, 62, 80));
    lblgioitinh.setText("jLabel2");

    lblchucvu.setFont(new java.awt.Font("Segoe UI", Font.PLAIN, 14)); // NOI18N
    lblchucvu.setForeground(new java.awt.Color(44, 62, 80));
    lblchucvu.setText("jLabel2");

    lblluong.setFont(new java.awt.Font("Segoe UI", Font.PLAIN, 14)); // NOI18N
    lblluong.setForeground(new java.awt.Color(44, 62, 80));
    lblluong.setText("jLabel2");

    lblemail.setFont(new java.awt.Font("Segoe UI", Font.PLAIN, 14)); // NOI18N
    lblemail.setForeground(new java.awt.Color(44, 62, 80));
    lblemail.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    lblemail.setText("jLabel2");

    jLabel2.setFont(new java.awt.Font("Segoe UI", Font.BOLD, 14)); // NOI18N
    jLabel2.setForeground(new java.awt.Color(100, 100, 100));
    jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
    jLabel2.setText("ID:");

    lblid.setFont(new java.awt.Font("Segoe UI", Font.PLAIN, 14)); // NOI18N
    lblid.setForeground(new java.awt.Color(44, 62, 80));
    lblid.setText("jLabel2");

    jLabel6.setFont(new java.awt.Font("Segoe UI", Font.BOLD, 14)); // NOI18N
    jLabel6.setForeground(new java.awt.Color(100, 100, 100));
    jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
    jLabel6.setText("Giới tính:");

    jLabel7.setFont(new java.awt.Font("Segoe UI", Font.BOLD, 14)); // NOI18N
    jLabel7.setForeground(new java.awt.Color(100, 100, 100));
    jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
    jLabel7.setText("Chức vụ:");

    jLabel8.setFont(new java.awt.Font("Segoe UI", Font.BOLD, 14)); // NOI18N
    jLabel8.setForeground(new java.awt.Color(100, 100, 100));
    jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
    jLabel8.setText("Email:");

    lblHovaTen.setFont(new java.awt.Font("Segoe UI", Font.BOLD, 18)); // NOI18N
    lblHovaTen.setForeground(new java.awt.Color(52, 73, 94));
    lblHovaTen.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    lblHovaTen.setText("jLabel2");

    jLabel1.setBackground(Memory.colorThemes_2);
    jLabel1.setForeground(new java.awt.Color(204, 204, 255));
    jLabel1.setOpaque(true);
    jLabel1.setPreferredSize(new java.awt.Dimension(130, 100));

    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel1Layout.createSequentialGroup()
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(39, 39, 39)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 87, Short.MAX_VALUE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblid, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(lblgioitinh, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE)
                                        .addGap(15, 15, 15)))))
                        .addComponent(lblHovaTen, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblemail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(10, 10, 10)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(5, 5, 5))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lblchucvu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(lblluong, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(0, 15, Short.MAX_VALUE)))))
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        .addGroup(jPanel1Layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
    jPanel1Layout.setVerticalGroup(
        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel1Layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(13, 13, 13)
            .addComponent(lblHovaTen)
            .addGap(20, 20, 20)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel2)
                .addComponent(lblid))
            .addGap(20, 20, 20)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel6)
                .addComponent(lblgioitinh))
            .addGap(20, 20, 20)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(lblchucvu)
                .addComponent(jLabel7))
            .addGap(20, 20, 20)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel9)
                .addComponent(lblluong))
            .addGap(20, 20, 20)
            .addComponent(jLabel8)
            .addGap(0, 0, Short.MAX_VALUE)
            .addComponent(lblemail)
            .addGap(23, 23, 23))
    );

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(0, 0, Short.MAX_VALUE))
    );
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
    );

    pack();
    setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserInfor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserInfor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserInfor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserInfor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserInfor().setVisible(true);
            }
        });
    }
}
